import type { Meta, StoryObj } from '@storybook/react';

import Utregning from '@/refusjon/RefusjonSide/Utregning';
import { Tiltak } from '@/refusjon/refusjon';

const meta = {
    title: 'Refusjons Saksbehandler/Utregning',
    args: {},
    parameters: {
        layout: 'fullscreen',
    },
} satisfies Meta;

export default meta;
type Story = StoryObj<typeof meta>;

const refusjonsdata = {
    refusjonsnummer: { avtalenr: 123, løpenummer: 3 },
    erKorreksjon: false,
    beregning: {
        lønn: 20423,
        lønnFratrukketFerie: 20423,
        feriepenger: 2451,
        tjenestepensjon: 457,
        arbeidsgiveravgift: 3290,
        sumUtgifter: 26621,
        beregnetBeløp: 10648,
        refusjonsbeløp: -6558,
        overTilskuddsbeløp: false,
        tidligereUtbetalt: 0,
        fratrekkLønnFerie: 0,
        tidligereRefundertBeløp: 0,
        sumUtgifterFratrukketRefundertBeløp: 26621,
        overFemGrunnbeløp: false,
        id: '01HKM6JYZ4ATAQH5VZ28YZA6RG',
    },
    tilskuddsgrunnlag: {
        avtaleId: '50844b27-1d75-43b2-bbe5-fe27c75d8340',
        avtaleFom: undefined,
        avtaleTom: undefined,
        tilskuddsperiodeId: '6f79233e-857d-4f64-8c86-6666afb56cdc',
        deltakerFornavn: 'Bjørnstjerne',
        deltakerEtternavn: 'Bjørnson',
        deltakerFnr: '28128521498',
        veilederNavIdent: 'X123456',
        bedriftNavn: 'Kiwi Majorstuen',
        bedriftNr: '999999999',
        tilskuddFom: '2023-12-01',
        tilskuddTom: '2023-12-31',
        feriepengerSats: 0.12,
        otpSats: 0.02,
        arbeidsgiveravgiftSats: 0.141,
        tiltakstype: Tiltak.MIDLERTIDIG_LØNNSTILSKUDD,
        tilskuddsbeløp: 20579,
        lønnstilskuddsprosent: 40,
        avtaleNr: 3456,
        løpenummer: 3,
        resendingsnummer: 1,
        enhet: '1000',
        id: '01HKM5N9F8987C49Y2N06PDJ3E',
    },
    forrigeRefusjonMinusBeløp: -17206,
    inntektsgrunnlag: {
        inntekter: [
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'loennUtbetaltAvVeldedigEllerAllmennyttigInstitusjonEllerOrganisasjon',
                beløp: 423,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: true,
                id: '01HKM6HPY7200C0VN1451E7CQ5',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'uregelmessigeTilleggKnyttetTilArbeidetTid',
                beløp: 10000,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: true,
                id: '01HKM6HPY7RQD6025EY0180K1K',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'trekkILoennForFerie',
                beløp: -1200,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: false,
                id: '01HKM6HPY7JWT2GJ6HMP9RZHVJ',
                erMedIInntektsgrunnlag: false,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'fastloenn',
                beløp: 10000,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: true,
                id: '01HKM6HPY4SHRG6FPE88QBCCXH',
                erMedIInntektsgrunnlag: true,
            },
        ],
        bruttoLønn: 20423,
        id: '01HKM6HPY7VC0KTQRTGPGAZ547',
        innhentetTidspunkt: '2024-01-08T10:30:35.335458',
    },
};

const korreksjonsdata = {
    refusjonsnummer: { avtalenr: 123, løpenummer: 3 },
    erKorreksjon: true,
    beregning: {
        lønn: 44846,
        lønnFratrukketFerie: 43646,
        feriepenger: 5238,
        tjenestepensjon: 978,
        arbeidsgiveravgift: 7030,
        sumUtgifter: 56892,
        beregnetBeløp: 22757,
        refusjonsbeløp: 27137,
        overTilskuddsbeløp: true,
        tidligereUtbetalt: -6558,
        fratrekkLønnFerie: -1200,
        tidligereRefundertBeløp: 0,
        sumUtgifterFratrukketRefundertBeløp: 56892,
        overFemGrunnbeløp: false,
        id: '01HKMSXH68PBQ8XABNBHPKWGYG',
    },
    tilskuddsgrunnlag: {
        avtaleId: '50844b27-1d75-43b2-bbe5-fe27c75d8340',
        avtaleFom: undefined,
        avtaleTom: undefined,
        tilskuddsperiodeId: '6f79233e-857d-4f64-8c86-6666afb56cdc',
        deltakerFornavn: 'Bjørnstjerne',
        deltakerEtternavn: 'Bjørnson',
        deltakerFnr: '28128521498',
        arbeidsgiverFornavn: 'Arne',
        arbeidsgiverEtternavn: 'Arbeidsgiver',
        arbeidsgiverTlf: '41111111',
        veilederNavIdent: 'X123456',
        bedriftNavn: 'Kiwi Majorstuen',
        bedriftNr: '999999999',
        tilskuddFom: '2023-12-01',
        tilskuddTom: '2023-12-31',
        feriepengerSats: 0.12,
        otpSats: 0.02,
        arbeidsgiveravgiftSats: 0.141,
        tiltakstype: Tiltak.MIDLERTIDIG_LØNNSTILSKUDD,
        tilskuddsbeløp: 20579,
        lønnstilskuddsprosent: 40,
        avtaleNr: 3456,
        løpenummer: 3,
        resendingsnummer: 1,
        enhet: '1000',
        godkjentAvBeslutterTidspunkt: '2023-10-01T10:15:04.040058',
        id: '01HKM5N9F8987C49Y2N06PDJ3E',
    },
    forrigeRefusjonMinusBeløp: 0,
    inntektsgrunnlag: {
        inntekter: [
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'loennUtbetaltAvVeldedigEllerAllmennyttigInstitusjonEllerOrganisasjon',
                beløp: 423,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: true,
                id: '01HKMSX7EDXDD7QFHDNRDHRS4G',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'fastloenn',
                beløp: 10000,
                måned: '2024-01',
                opptjeningsperiodeFom: '2024-01-01',
                opptjeningsperiodeTom: '2024-01-31',
                erOpptjentIPeriode: true,
                id: '01HKMSX7EDE85EGH59B82XBPCX',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'fastloenn',
                beløp: 2000,
                måned: '2024-01',
                opptjeningsperiodeFom: '2024-01-01',
                opptjeningsperiodeTom: '2024-01-31',
                erOpptjentIPeriode: true,
                id: '01HKMSX7EDMRCE0AG3XAS8PJRY',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'trekkILoennForFerie',
                beløp: -1200,
                måned: '2024-01',
                opptjeningsperiodeFom: '2024-01-01',
                opptjeningsperiodeTom: '2024-01-31',
                erOpptjentIPeriode: false,
                id: '01HKMSX7EDGF9CGE65J2APJDWP',
                erMedIInntektsgrunnlag: false,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'uregelmessigeTilleggKnyttetTilArbeidetTid',
                beløp: 10000,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: true,
                id: '01HKMSX7EDSPJM34GSH0M4WMN3',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'trekkILoennForFerie',
                beløp: -1200,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: false,
                id: '01HKMSX7EDQGXGN6F2Z2BAGQDS',
                erMedIInntektsgrunnlag: false,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'fastloenn',
                beløp: 10000,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: true,
                id: '01HKMSX7EDPX5JRE0BGWHH5YGP',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'fastloenn',
                beløp: 2000,
                måned: '2023-12',
                opptjeningsperiodeFom: '2023-12-01',
                opptjeningsperiodeTom: '2023-12-31',
                erOpptjentIPeriode: true,
                id: '01HKMSX7EDGAM0X1J806MBWAQ5',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'loennUtbetaltAvVeldedigEllerAllmennyttigInstitusjonEllerOrganisasjon',
                beløp: 423,
                måned: '2024-01',
                opptjeningsperiodeFom: '2024-01-01',
                opptjeningsperiodeTom: '2024-01-31',
                erOpptjentIPeriode: true,
                id: '01HKMSX7EDGYPB7GEW2C78Y385',
                erMedIInntektsgrunnlag: true,
            },
            {
                inntektType: 'LOENNSINNTEKT',
                beskrivelse: 'uregelmessigeTilleggKnyttetTilArbeidetTid',
                beløp: 10000,
                måned: '2024-01',
                opptjeningsperiodeFom: '2024-01-01',
                opptjeningsperiodeTom: '2024-01-31',
                erOpptjentIPeriode: true,
                id: '01HKMSX7ED9CY65VY2W0JESHAF',
                erMedIInntektsgrunnlag: true,
            },
        ],
        bruttoLønn: 44846,
        id: '01HKMSX7EDBF2VCT9H35NBC2NA',
        innhentetTidspunkt: '2024-01-08T16:08:55.629546',
    },
};

export const MinusbelopKorreksjon: Story = {
    name: 'Korrigering av minusbeløp',
    args: {},
    render: (args) => (
        <div>
            <h1>Korreksjon: Juster opp lønn for å fjerne minusbeløp</h1>
            <h2>Utregning: Refusjon</h2>
            <p>
                Her har arbeidsgiver valgt inntektslinjer som gir for lav lønn i forhold til ferietrekk, og beløpet går
                i minus (tjente ikke nok for å dekke ferietrekket).
            </p>
            <Utregning {...refusjonsdata} />
            <h2>Utregning: Korreksjon</h2>
            <p>
                I korreksjonen har vi valgt flere inntektslinjer slik at tilskuddsbeløpet overskrides. Ettersom
                deltakeren nå har tjent nok til å dekke ferietrekket må vi også tilbakebetale "mellomlegg" for å nulle
                ut minusbeløpet i refusjonen.
            </p>
            <Utregning {...korreksjonsdata} />
        </div>
    ),
};
