apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-saksbehandler
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://tiltak-refusjon.intern.nav.no
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      extra:
        - "NAVident"
    sidecar:
      enabled: true
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 2
  env:
    - name: MILJO
      value: prod-gcp
    - name: AAD_REDIRECT_URL
      value: https://tiltak-refusjon.intern.nav.no/oauth2/callback
    - name: AAD_LOGOUT_REDIRECT_URL
      value: https://tiltak-refusjon.intern.nav.no/oauth2/callback
    - name: API_CLIENT_ID
      value: prod-gcp.arbeidsgiver.tiltak-refusjon-api
    - name: DECORATOR_HOST
      value: https://internarbeidsflatedecorator.intern.nav.no
    - name: API_URL
      value: http://tiltak-refusjon-api
    - name: HOST
      value: https://tiltak-refusjon.intern.nav.no
  accessPolicy:
    outbound:
      rules:
        - application: tiltak-refusjon-api
      external:
        - host: internarbeidsflatedecorator.intern.nav.no
        - host: login.microsoftonline.com
        - host: www.nav.no
  envFrom:
    - secret: tiltak-refusjon-session-encrypt-key
