apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-saksbehandler-storybook
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - https://tiltak-refusjon-storybook.intern.dev.nav.no
  liveness:
    path: /
    initialDelay: 10
  readiness:
    path: /
    initialDelay: 10
  replicas:
    min: 1
    max: 1
