apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-saksbehandler-storybook
  namespace: team-tiltak
  labels:
    team: team-tiltak
spec:
  image: {{image}}
  port: 80
  ingresses:
    - https://tiltak-refusjon-storybook.intern.dev.nav.no
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  replicas:
    min: 1
    max: 1
