apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: arbeidsgiver
  name: tiltak-refusjon-saksbehandler-redis
  namespace: arbeidsgiver
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-group: "0"
spec:
  image: bitnami/redis:5.0.14
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: tiltak-refusjon-saksbehandler
  envFrom:
    - secret: tiltak-refusjon-saksbehandler-redis
