import KorreksjonKvitteringSide from '@/KorreksjonKvitteringSide/KorreksjonKvitteringSide';
import { Korreksjon, Korreksjonsgrunn, Tiltak, KorreksjonStatus, Refusjon, RefusjonStatus } from '@/refusjon/refusjon';
import { Meta, StoryObj } from '@storybook/react';

const meta = {
    title: 'Refusjons Saksbehandler/Korreksjon kvittering',
    component: KorreksjonKvitteringSide,
    parameters: {
        // More on how to position stories at: https://storybook.js.org/docs/configure/story-layout
        layout: 'fullscreen',
    },
} satisfies Meta<typeof KorreksjonKvitteringSide>;

export default meta;
type Story = StoryObj<typeof meta>;

const refusjon: Refusjon = {
    harInntektIAlleMåneder: true,
    refusjonsgrunnlag: {
        harFerietrekkForSammeMåned: false,
        tilskuddsgrunnlag: {
            avtaleId: 'd5c44c9c-1a97-4db3-abbd-5c738aec0613',
            tilskuddsperiodeId: '2f6c1c6a-a1d5-4797-8690-8530a8bbf92f',
            deltakerFornavn: 'Formye',
            deltakerEtternavn: 'Ferietrekksen',
            deltakerFnr: '28061827902',
            veilederNavIdent: 'Z123456',
            bedriftNavn: 'Kiwi Majorstuen',
            bedriftNr: '999999999',
            tilskuddFom: '2023-12-01',
            tilskuddTom: '2023-12-31',
            feriepengerSats: 0.12,
            otpSats: 0.02,
            arbeidsgiveravgiftSats: 0.141,
            tiltakstype: Tiltak.SOMMERJOBB,
            tilskuddsbeløp: 13337,
            lønnstilskuddsprosent: 40,
            avtaleNr: 3456,
            løpenummer: 3,
            enhet: '1000',
            id: '01HMRY4Y4RAJJN459TD4GR5BGH',
        },
        inntektsgrunnlag: {
            inntekter: [
                {
                    inntektType: 'LOENNSINNTEKT',
                    beskrivelse: 'fastloenn',
                    beløp: 30000.0,
                    måned: '2023-12',
                    opptjeningsperiodeFom: '2023-12-31',
                    opptjeningsperiodeTom: '2023-12-31',
                    erOpptjentIPeriode: true,
                    id: '01HMRY5C76KY3AB59RK8HZY0VS',
                    erMedIInntektsgrunnlag: true,
                },
                {
                    inntektType: 'LOENNSINNTEKT',
                    beskrivelse: 'trekkILoennForFerie',
                    beløp: -35000.0,
                    måned: '2023-12',
                    opptjeningsperiodeFom: '2024-01-31',
                    opptjeningsperiodeTom: '2023-12-31',
                    erOpptjentIPeriode: undefined,
                    id: '01HMRY5C73NSNAV9V59CZWQJMC',
                    erMedIInntektsgrunnlag: false,
                },
                {
                    inntektType: 'LOENNSINNTEKT',
                    beskrivelse: 'fastloenn',
                    beløp: 2000.0,
                    måned: '2023-12',
                    opptjeningsperiodeFom: '2023-12-31',
                    opptjeningsperiodeTom: '2023-12-31',
                    erOpptjentIPeriode: true,
                    id: '01HMRY5C76JA8JM24TCGF9K7C5',
                    erMedIInntektsgrunnlag: true,
                },
                {
                    inntektType: 'LOENNSINNTEKT',
                    beskrivelse: 'fastloenn',
                    beløp: 30000.0,
                    måned: '2023-12',
                    opptjeningsperiodeFom: '2024-01-31',
                    opptjeningsperiodeTom: '2023-12-31',
                    erOpptjentIPeriode: true,
                    id: '01HMRY5C73TZRM2Z25JMBDS304',
                    erMedIInntektsgrunnlag: true,
                },
            ],
            bruttoLønn: 2000.0,
            innhentetTidspunkt: '2024-01-22T16:55:56.518432',
        },
        bedriftKontonummer: '10000008145',
        bedriftKid: undefined,
        inntekterKunFraTiltaket: true,
        endretBruttoLønn: undefined,
        fratrekkRefunderbarBeløp: false,
        forrigeRefusjonMinusBeløp: 0,
        beregning: {
            lønn: 2000,
            lønnFratrukketFerie: -33000,
            feriepenger: -3960,
            tjenestepensjon: -739,
            arbeidsgiveravgift: -5316,
            sumUtgifter: -43015,
            beregnetBeløp: -17206,
            refusjonsbeløp: -17206,
            overTilskuddsbeløp: false,
            tidligereUtbetalt: 0,
            fratrekkLønnFerie: -35000,
            tidligereRefundertBeløp: 0,
            sumUtgifterFratrukketRefundertBeløp: -43015,
            overFemGrunnbeløp: false,
            id: '01HMRY5NRKY8X17XB8VQ9KTEFD',
        },
    },
    bedriftNr: '999999999',
    deltakerFnr: '28061827902',
    id: '01HMRY4Y4RRKBW8QT5VQAHRA58',
    fristForGodkjenning: '2024-02-29',
    forrigeFristForGodkjenning: undefined,
    unntakOmInntekterFremitid: 0,
    hentInntekterLengerFrem: 'foobar',
    godkjentAvArbeidsgiver: '2024-01-22T15:56:12.491915Z',
    status: RefusjonStatus.SENDT_KRAV,
    korreksjonId: '01HMRY76T65RTNQV0T43MDCE8B',
    harTattStillingTilAlleInntektslinjer: true,
};

const korreksjon: Korreksjon = {
    korrigererRefusjonId: '01HMRW629X08FN1WNPVJWTNTF1',
    refusjonsgrunnlag: {
        tilskuddsgrunnlag: {
            avtaleId: 'a2bfd3ef-6e81-4f63-b631-f4d00aebe68a',
            tilskuddsperiodeId: 'c936b415-3fdd-4234-8b7e-d12df08984b9',
            deltakerFornavn: 'Formye',
            deltakerEtternavn: 'Ferietrekksen',
            deltakerFnr: '28061827902',
            veilederNavIdent: 'Z123456',
            bedriftNavn: 'Kiwi Majorstuen',
            bedriftNr: '999999999',
            tilskuddFom: '2023-12-01',
            tilskuddTom: '2023-12-31',
            feriepengerSats: 0.12,
            otpSats: 0.02,
            arbeidsgiveravgiftSats: 0.141,
            tiltakstype: Tiltak.SOMMERJOBB,
            tilskuddsbeløp: 13337,
            lønnstilskuddsprosent: 40,
            avtaleNr: 3456,
            løpenummer: 3,
            enhet: '1000',
            id: '01HMRW629XHD1N2W33BDFTVJTJ',
        },
        inntektsgrunnlag: {
            inntekter: [
                {
                    inntektType: 'LOENNSINNTEKT',
                    beskrivelse: 'trekkILoennForFerie',
                    beløp: -35000.0,
                    måned: '2023-12',
                    opptjeningsperiodeFom: '2024-01-31',
                    opptjeningsperiodeTom: '2023-12-31',
                    erOpptjentIPeriode: undefined,
                    id: '01HMRW9MH7CRGT6JTW38HM7EQA',
                    erMedIInntektsgrunnlag: false,
                },
                {
                    inntektType: 'LOENNSINNTEKT',
                    beskrivelse: 'fastloenn',
                    beløp: 30000.0,
                    måned: '2023-12',
                    opptjeningsperiodeFom: '2024-01-31',
                    opptjeningsperiodeTom: '2023-12-31',
                    erOpptjentIPeriode: true,
                    id: '01HMRW9MH7H2V8NGVGH9AT9NF9',
                    erMedIInntektsgrunnlag: true,
                },
                {
                    inntektType: 'LOENNSINNTEKT',
                    beskrivelse: 'fastloenn',
                    beløp: 2000.0,
                    måned: '2023-12',
                    opptjeningsperiodeFom: '2023-12-31',
                    opptjeningsperiodeTom: '2023-12-31',
                    erOpptjentIPeriode: false,
                    id: '01HMRW9MH7QA6JM9PDPG6F5KBE',
                    erMedIInntektsgrunnlag: true,
                },
                {
                    inntektType: 'LOENNSINNTEKT',
                    beskrivelse: 'fastloenn',
                    beløp: 30000.0,
                    måned: '2023-12',
                    opptjeningsperiodeFom: '2023-12-31',
                    opptjeningsperiodeTom: '2023-12-31',
                    erOpptjentIPeriode: true,
                    id: '01HMRW9MH7BVRRVAPY7ZMKA92V',
                    erMedIInntektsgrunnlag: true,
                },
            ],
            bruttoLønn: 62000.0,
            innhentetTidspunkt: '2024-01-22T16:23:18.951698',
        },
        bedriftKontonummer: '10000008145',
        bedriftKid: undefined,
        inntekterKunFraTiltaket: true,
        endretBruttoLønn: undefined,
        harFerietrekkForSammeMåned: false,
        fratrekkRefunderbarBeløp: false,
        forrigeRefusjonMinusBeløp: 0,
        beregning: {
            lønn: 60000,
            lønnFratrukketFerie: 25000,
            feriepenger: 3000,
            tjenestepensjon: 560,
            arbeidsgiveravgift: 4027,
            sumUtgifter: 32587,
            beregnetBeløp: 13035,
            refusjonsbeløp: -302,
            overTilskuddsbeløp: false,
            tidligereUtbetalt: 13337,
            fratrekkLønnFerie: -35000,
            tidligereRefundertBeløp: 0,
            sumUtgifterFratrukketRefundertBeløp: 32587,
            overFemGrunnbeløp: true,
            id: '01HMRW9XMVT78J74YMEZSVM1KD',
        },
    },
    deltakerFnr: '28061827902',
    bedriftNr: '999999999',
    id: '01HMRW9JTD7GRJGSPSGAJQN20N',
    korreksjonsgrunner: [Korreksjonsgrunn.HENT_INNTEKTER_PÅ_NYTT],
    status: KorreksjonStatus.TILBAKEKREVING,
    kostnadssted: undefined,
    harInntektIAlleMåneder: false,
    harTattStillingTilAlleInntektslinjer: true,
};

export const KorreksjonMedPlussbelopOgTilbakekreving: Story = {
    name: 'Korreksjon med plussbeløp og tilbakekreving',
    args: { refusjon: refusjon, korreksjon: korreksjon },
    decorators: [
        (Story, args) => (
            <div>
                <h1>KvitteringKorreksjon: Korreksjon med plussbeløp og tilbakekreving</h1>
                <Story {...args} />
            </div>
        ),
    ],
};
