export enum Status {
    KLAR_FOR_INNSENDING = 'KLAR_FOR_INNSENDING',
    FOR_TIDLIG = 'FOR_TIDLIG',
    SENDT_KRAV = 'SENDT_KRAV',
    UTBETALT = 'UTBETALT',
    UTBETALING_FEILET = 'UTBETALING_FEILET',
    UTGÅTT = 'UTGÅTT',
    ANNULLERT = 'ANNULLERT',
    KORREKSJON_UTKAST = 'KORREKSJON_UTKAST',
    KORREKSJON_SENDT_TIL_UTBETALING = 'KORREKSJON_SENDT_TIL_UTBETALING',
    KORREKSJON_OPPGJORT = 'KORREKSJON_OPPGJORT',
    KORREKSJON_SKAL_TILBAKEKREVES = 'KORREKSJON_SKAL_TILBAKEKREVES',
}
