export enum Status {
    KLAR_FOR_INNSENDING = 'KLAR_FOR_INNSENDING',
    FOR_TIDLIG = 'FOR_TIDLIG',
    SENDT_KRAV = 'SENDT_KRAV',
    UTBETALT = 'UTBETALT',
    UTGÅTT = 'UTGÅTT',
    ANNULLERT = 'ANNULLERT',
    MANUELL_KORREKSJON = 'MANUELL_KORREKSJON',
    KORREKSJON_SENDT_TIL_UTBETALING = 'KORREKSJON_SENDT_TIL_UTBETALING',
}
